// Template: DomainServiceTest.java.tpl
// Output: {{basePackagePath}}/domain/service/{{Entity}}DomainServiceTest.java
// Purpose: Unit test for domain service (pure POJO, no Spring)

package {{basePackage}}.domain.service;

import {{basePackage}}.domain.model.*;
import {{basePackage}}.domain.repository.{{Entity}}Repository;
import {{basePackage}}.domain.exception.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{Entity}}DomainService.
 * 
 * NO Spring context needed - pure POJO testing.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
@ExtendWith(MockitoExtension.class)
class {{Entity}}DomainServiceTest {
    
    @Mock
    private {{Entity}}Repository repository;
    
    private {{Entity}}DomainService domainService;
    
    @BeforeEach
    void setUp() {
        domainService = new {{Entity}}DomainService(repository);
    }
    
    @Test
    void get{{Entity}}_WhenExists_ReturnsEntity() {
        // Given
        {{Entity}}Id id = {{Entity}}Id.generate();
        {{Entity}} entity = {{Entity}}.reconstitute(id{{#entityFields}}, {{testValue}}{{/entityFields}});
        when(repository.findById(id)).thenReturn(Optional.of(entity));
        
        // When
        {{Entity}} result = domainService.get{{Entity}}(id);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getId()).isEqualTo(id);
    }
    
    @Test
    void get{{Entity}}_WhenNotExists_ThrowsException() {
        // Given
        {{Entity}}Id id = {{Entity}}Id.generate();
        when(repository.findById(id)).thenReturn(Optional.empty());
        
        // When/Then
        assertThatThrownBy(() -> domainService.get{{Entity}}(id))
            .isInstanceOf({{Entity}}NotFoundException.class);
    }
    
    @Test
    void create{{Entity}}_SavesAndReturnsEntity() {
        // Given
        when(repository.save(any({{Entity}}.class))).thenAnswer(inv -> inv.getArgument(0));
        
        // When
        {{Entity}} result = domainService.create{{Entity}}({{#entityFields}}{{testValue}}{{^last}}, {{/last}}{{/entityFields}});
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getId()).isNotNull();
        verify(repository).save(any({{Entity}}.class));
    }
}
