package {{basePackage}}.infrastructure;

import {{basePackage}}.domain.exception.{{Entity}}NotFoundException;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.net.URI;
import java.time.Instant;
import java.util.stream.Collectors;

/**
 * Global exception handler for {{serviceName}}.
 * Uses RFC 7807 Problem Details format.
 * 
 * Generated by: skill-code-020-generate-microservice-java-spring
 * Module: mod-015-hexagonal-base-java-spring
 */
@RestControllerAdvice
@Slf4j
public class GlobalExceptionHandler {
    
    private static final String TYPE_BASE = "https://api.{{organization}}.com/problems";
    
    /**
     * Handle entity not found exceptions.
     */
    @ExceptionHandler({{Entity}}NotFoundException.class)
    public ProblemDetail handle{{Entity}}NotFound({{Entity}}NotFoundException ex) {
        log.warn("{{Entity}} not found: {}", ex.getMessage());
        
        ProblemDetail problem = ProblemDetail.forStatusAndDetail(
            HttpStatus.NOT_FOUND,
            ex.getMessage()
        );
        problem.setType(URI.create(TYPE_BASE + "/{{entity}}-not-found"));
        problem.setTitle("{{Entity}} Not Found");
        problem.setProperty("timestamp", Instant.now());
        
        return problem;
    }
    
    /**
     * Handle validation errors.
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ProblemDetail handleValidation(MethodArgumentNotValidException ex) {
        String errors = ex.getBindingResult().getFieldErrors().stream()
            .map(e -> e.getField() + ": " + e.getDefaultMessage())
            .collect(Collectors.joining(", "));
        
        log.warn("Validation failed: {}", errors);
        
        ProblemDetail problem = ProblemDetail.forStatusAndDetail(
            HttpStatus.BAD_REQUEST,
            "Validation failed"
        );
        problem.setType(URI.create(TYPE_BASE + "/validation-error"));
        problem.setTitle("Validation Error");
        problem.setProperty("errors", errors);
        problem.setProperty("timestamp", Instant.now());
        
        return problem;
    }
    
    /**
     * Handle illegal argument exceptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ProblemDetail handleIllegalArgument(IllegalArgumentException ex) {
        log.warn("Invalid argument: {}", ex.getMessage());
        
        ProblemDetail problem = ProblemDetail.forStatusAndDetail(
            HttpStatus.BAD_REQUEST,
            ex.getMessage()
        );
        problem.setType(URI.create(TYPE_BASE + "/invalid-argument"));
        problem.setTitle("Invalid Argument");
        problem.setProperty("timestamp", Instant.now());
        
        return problem;
    }
    
    /**
     * Handle unexpected exceptions.
     */
    @ExceptionHandler(Exception.class)
    public ProblemDetail handleGeneric(Exception ex) {
        log.error("Unexpected error", ex);
        
        ProblemDetail problem = ProblemDetail.forStatusAndDetail(
            HttpStatus.INTERNAL_SERVER_ERROR,
            "An unexpected error occurred"
        );
        problem.setType(URI.create(TYPE_BASE + "/internal-error"));
        problem.setTitle("Internal Server Error");
        problem.setProperty("timestamp", Instant.now());
        
        return problem;
    }
}
