package {{basePackage}}.application.dto;

import jakarta.validation.constraints.*;
{{#fields}}
{{#if validation.pattern}}
import jakarta.validation.constraints.Pattern;
{{/if}}
{{/fields}}

/**
 * Request DTO for creating a new {{Entity}}.
 * 
 * Generated by: skill-code-020-generate-microservice-java-spring
 * Module: mod-015-hexagonal-base-java-spring
 */
public record Create{{Entity}}Request(
    {{#fields}}
    {{#if required}}
    @NotNull(message = "{{fieldName}} is required")
    {{/if}}
    {{#if validation.maxLength}}
    @Size(max = {{validation.maxLength}}, message = "{{fieldName}} must not exceed {{validation.maxLength}} characters")
    {{/if}}
    {{#if validation.pattern}}
    @Pattern(regexp = "{{validation.pattern}}", message = "{{fieldName}} format is invalid")
    {{/if}}
    {{#if validation.email}}
    @Email(message = "{{fieldName}} must be a valid email address")
    {{/if}}
    {{type}} {{fieldName}}{{#unless @last}},{{/unless}}
    {{/fields}}
) {
    
    /**
     * Factory method with validation.
     */
    public static Create{{Entity}}Request of(
        {{#fields}}
        {{type}} {{fieldName}}{{#unless @last}},{{/unless}}
        {{/fields}}
    ) {
        return new Create{{Entity}}Request(
            {{#fields}}
            {{fieldName}}{{#unless @last}},{{/unless}}
            {{/fields}}
        );
    }
}
