package {{basePackage}}.application.dto;

import {{basePackage}}.domain.model.{{Entity}};
import java.time.Instant;

/**
 * Response DTO for {{Entity}}.
 * 
 * Generated by: skill-code-020-generate-microservice-java-spring
 * Module: mod-015-hexagonal-base-java-spring
 */
public record {{Entity}}Response(
    {{#fields}}
    {{type}} {{fieldName}}{{#unless @last}},{{/unless}}
    {{/fields}}
) {
    
    /**
     * Factory method to create response from domain entity.
     */
    public static {{Entity}}Response from({{Entity}} entity) {
        if (entity == null) {
            return null;
        }
        return new {{Entity}}Response(
            {{#fields}}
            entity.get{{FieldName}}(){{#unless @last}},{{/unless}}
            {{/fields}}
        );
    }
}
