// Template: CircuitBreakerTest.java.tpl
// Output: {{basePackagePath}}/service/{{serviceName}}Test.java
// Purpose: Unit test for circuit breaker behavior

package {{basePackage}}.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{serviceName}} circuit breaker behavior.
 * 
 * Generated by: mod-001-circuit-breaker-java-resilience4j
 * ERI Reference: eri-code-008-circuit-breaker-java-resilience4j
 */
@ExtendWith(MockitoExtension.class)
class {{serviceName}}Test {
    
    @Mock
    private {{clientType}} client;
    
    @InjectMocks
    private {{serviceName}} service;
    
    @Test
    void {{methodName}}_WhenServiceAvailable_ReturnsResult() {
        // Given
        {{returnType}} expected = {{expectedValue}};
        when(client.call(any())).thenReturn(expected);
        
        // When
        {{returnType}} result = service.{{methodName}}({{testParams}});
        
        // Then
        assertThat(result).isEqualTo(expected);
        verify(client).call(any());
    }
    
    @Test
    void {{methodName}}_WhenServiceUnavailable_ReturnsFallback() {
        // Given
        when(client.call(any())).thenThrow(new RuntimeException("Service down"));
        
        // When
        {{returnType}} result = service.{{methodName}}({{testParams}});
        
        // Then
        assertThat(result).isNotNull();
        // Verify fallback behavior based on strategy
    }
    
    @Test
    void {{methodName}}_WhenCircuitOpen_ReturnsFallbackImmediately() {
        // Given - simulate circuit open by repeated failures
        when(client.call(any())).thenThrow(new RuntimeException("Service down"));
        
        // Trigger enough failures to open circuit
        for (int i = 0; i < {{minimumNumberOfCalls}}; i++) {
            try {
                service.{{methodName}}({{testParams}});
            } catch (Exception ignored) {}
        }
        
        // When - next call should use fallback immediately
        {{returnType}} result = service.{{methodName}}({{testParams}});
        
        // Then
        assertThat(result).isNotNull();
        // Circuit should be open, client not called again
    }
}
