// Template: ClientTest.java.tpl
// Output: {{basePackagePath}}/adapter/integration/client/{{ApiName}}ClientTest.java
// Purpose: Unit test for REST client

package {{basePackage}}.adapter.integration.client;

import {{basePackage}}.adapter.integration.dto.{{Entity}}Dto;
import com.github.tomakehurst.wiremock.junit5.WireMockTest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static com.github.tomakehurst.wiremock.client.WireMock.*;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for {{ApiName}}Client.
 * Uses WireMock to stub external API.
 * 
 * Generated by: mod-018-api-integration-rest-java-spring
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@SpringBootTest
@WireMockTest(httpPort = 8081)
class {{ApiName}}ClientTest {
    
    @Autowired
    private {{ApiName}}Client client;
    
    @Test
    void getById_returnsEntity() {
        // Given
        String id = "123";
        stubFor(get(urlEqualTo("{{resourcePath}}/" + id))
            .willReturn(okJson("""
                {
                    "id": "123",
                    "name": "Test"
                }
                """)));
        
        // When
        {{Entity}}Dto result = client.getById(id);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getId()).isEqualTo("123");
        
        verify(getRequestedFor(urlEqualTo("{{resourcePath}}/" + id))
            .withHeader("X-Source-System", equalTo("{{serviceName}}")));
    }
    
    @Test
    void create_sendsEntityAndReturnsCreated() {
        // Given
        {{Entity}}Dto input = {{Entity}}Dto.builder()
            .name("New Entity")
            .build();
            
        stubFor(post(urlEqualTo("{{resourcePath}}"))
            .willReturn(okJson("""
                {
                    "id": "456",
                    "name": "New Entity"
                }
                """)));
        
        // When
        {{Entity}}Dto result = client.create(input);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getId()).isEqualTo("456");
        
        verify(postRequestedFor(urlEqualTo("{{resourcePath}}"))
            .withHeader("Content-Type", equalTo("application/json")));
    }
}
