// Template: TimeoutTest.java.tpl
// Output: {{basePackagePath}}/application/service/{{Service}}ApplicationServiceTest.java
// Purpose: Unit test for timeout behavior

package {{basePackage}}.application.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{Service}}ApplicationService timeout behavior.
 * 
 * Generated by: mod-003-timeout-java-resilience4j
 * ERI Reference: eri-code-010-timeout-java-resilience4j
 */
@ExtendWith(MockitoExtension.class)
class {{Service}}ApplicationServiceTest {
    
    @Mock
    private {{ExternalClient}} client;
    
    @InjectMocks
    private {{Service}}ApplicationService service;
    
    @Test
    void {{methodName}}_completesWithinTimeout() throws Exception {
        // Arrange
        {{ReturnType}} expected = {{expectedValue}};
        when(client.{{clientMethod}}({{testParam}})).thenReturn(expected);
        
        // Act
        CompletableFuture<{{ReturnType}}> future = service.{{methodName}}({{testParam}});
        {{ReturnType}} result = future.get(1, TimeUnit.SECONDS);
        
        // Assert
        assertEquals(expected, result);
    }
    
    @Test
    void {{methodName}}_timesOut() {
        // Arrange - simulate slow response
        when(client.{{clientMethod}}({{testParam}})).thenAnswer(inv -> {
            Thread.sleep(10000);  // Longer than timeout
            return {{expectedValue}};
        });
        
        // Act
        CompletableFuture<{{ReturnType}}> future = service.{{methodName}}({{testParam}});
        
        // Assert
        assertThrows(TimeoutException.class, 
            () -> future.get({{timeoutDuration}} + 1, TimeUnit.SECONDS));
    }
}
