<!-- Output: pom.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>{{springBootVersion}}</version>
        <relativePath/>
    </parent>

    <groupId>{{groupId}}</groupId>
    <artifactId>{{serviceName}}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>{{serviceNamePascal}}</name>
    <description>{{serviceNamePascal}} - Generated by Enablement 2.0</description>

    <properties>
        <java.version>{{javaVersion}}</java.version>
        <lombok.version>1.18.30</lombok.version>
        <!-- Generate one property per entry in maven_dependencies.properties -->
    </properties>

    <!-- Include dependencyManagement only if maven_dependencies.dependency_management exists -->

    <dependencies>
        <!-- Generate one dependency per entry in maven_dependencies.dependencies -->
        <!-- Only include version tag if dependency has explicit version -->
        <!-- Only include scope tag if scope is not compile -->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${lombok-mapstruct-binding.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-Amapstruct.defaultComponentModel=spring</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
