// Template: PersistenceMapper.java.tpl
// Output: {{basePackage}}/adapter/persistence/mapper/{{Entity}}PersistenceMapper.java
// Purpose: Maps between domain entities and JPA entities

package {{basePackage}}.adapter.persistence.mapper;

import {{basePackage}}.adapter.persistence.entity.{{Entity}}JpaEntity;
import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.model.{{Entity}}Id;
import org.springframework.stereotype.Component;

/**
 * Mapper between {{Entity}} domain model and JPA entity.
 * 
 * Generated by: mod-016-persistence-jpa-spring
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Component
public class {{Entity}}PersistenceMapper {
    
    /**
     * Maps JPA entity to domain model.
     */
    public {{Entity}} toDomain({{Entity}}JpaEntity jpaEntity) {
        if (jpaEntity == null) {
            return null;
        }
        
        return {{Entity}}.reconstitute(
            {{Entity}}Id.of(jpaEntity.getId()){{#entityFields}},
            jpaEntity.get{{fieldNamePascal}}(){{/entityFields}}
        );
    }
    
    /**
     * Maps domain model to JPA entity.
     */
    public {{Entity}}JpaEntity toJpaEntity({{Entity}} domain) {
        if (domain == null) {
            return null;
        }
        
        return {{Entity}}JpaEntity.builder()
            .id(domain.getId().value())
{{#entityFields}}
            .{{fieldName}}(domain.get{{fieldNamePascal}}())
{{/entityFields}}
            .build();
    }
}
