// Template: AssemblerTest.java.tpl
// Output: {{basePackagePath}}/infrastructure/adapter/in/rest/{{Entity}}ModelAssemblerTest.java
// Purpose: Unit test for HATEOAS model assembler

package {{basePackage}}.infrastructure.adapter.in.rest;

import {{basePackage}}.application.dto.{{Entity}}Response;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.springframework.hateoas.EntityModel;
import org.springframework.hateoas.Link;

import java.util.UUID;

import static org.assertj.core.api.Assertions.*;

/**
 * Unit tests for {{Entity}}ModelAssembler.
 * 
 * Tests HATEOAS link generation.
 * 
 * Generated by: mod-019-api-public-exposure-java-spring
 * ERI Reference: eri-code-014-api-public-exposure-java-spring
 */
class {{Entity}}ModelAssemblerTest {

    private {{Entity}}ModelAssembler assembler;

    @BeforeEach
    void setUp() {
        assembler = new {{Entity}}ModelAssembler();
    }

    @Test
    @DisplayName("should create entity model with self link")
    void toModel_CreatesEntityModelWithSelfLink() {
        // Given
        UUID id = UUID.randomUUID();
        {{Entity}}Response response = {{Entity}}Response.builder()
            .id(id)
            {{#entityFields}}
            .{{name}}({{testValue}})
            {{/entityFields}}
            .build();

        // When
        EntityModel<{{Entity}}Response> model = assembler.toModel(response);

        // Then
        assertThat(model).isNotNull();
        assertThat(model.getContent()).isEqualTo(response);
        assertThat(model.getLink("self")).isPresent();
    }

    @Test
    @DisplayName("should include correct self link URL")
    void toModel_SelfLinkContainsEntityId() {
        // Given
        UUID id = UUID.randomUUID();
        {{Entity}}Response response = {{Entity}}Response.builder()
            .id(id)
            {{#entityFields}}
            .{{name}}({{testValue}})
            {{/entityFields}}
            .build();

        // When
        EntityModel<{{Entity}}Response> model = assembler.toModel(response);

        // Then
        Link selfLink = model.getRequiredLink("self");
        assertThat(selfLink.getHref()).contains(id.toString());
    }

    @Test
    @DisplayName("should include collection link")
    void toModel_IncludesCollectionLink() {
        // Given
        UUID id = UUID.randomUUID();
        {{Entity}}Response response = {{Entity}}Response.builder()
            .id(id)
            {{#entityFields}}
            .{{name}}({{testValue}})
            {{/entityFields}}
            .build();

        // When
        EntityModel<{{Entity}}Response> model = assembler.toModel(response);

        // Then
        assertThat(model.getLink("{{entityPlural}}")).isPresent();
    }
}
