// ═══════════════════════════════════════════════════════════════════════════════
// Template: ControllerTest-hateoas.java.tpl
// Module: mod-code-019-api-public-exposure-java-spring
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackagePath}}/infrastructure/adapter/in/rest/{{Entity}}ControllerTest.java
// Purpose: Unit test for REST controller WITH HATEOAS (WebMvcTest)
// ═══════════════════════════════════════════════════════════════════════════════
// TTB-001 FIX: This template properly mocks the ModelAssembler for HATEOAS tests
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}}.infrastructure.adapter.in.rest;

import {{basePackage}}.application.{{Entity}}ApplicationService;
import {{basePackage}}.application.dto.*;
import {{basePackage}}.domain.model.*;
import {{basePackage}}.domain.exception.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.hateoas.EntityModel;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.UUID;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Unit tests for {{Entity}}Controller with HATEOAS support.
 * 
 * Uses @WebMvcTest for isolated controller testing.
 * Both ApplicationService AND ModelAssembler are mocked.
 * 
 * Generated by: mod-019-api-public-exposure-java-spring
 * ERI Reference: eri-code-014-api-public-exposure-java-spring
 */
@WebMvcTest({{Entity}}Controller.class)
class {{Entity}}ControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private {{Entity}}ApplicationService applicationService;

    // TTB-001 FIX: Mock the assembler to avoid NPE
    @MockBean
    private {{Entity}}ModelAssembler assembler;

    private static final String BASE_URL = "/api/v1/{{entityPlural}}";

    @Test
    @DisplayName("GET /{id} - should return entity when exists")
    void getById_WhenExists_ReturnsEntity() throws Exception {
        // Given
        String id = UUID.randomUUID().toString();
        {{Entity}}Response response = new {{Entity}}Response(
            id
            {{#entityFields}}, {{testValue}}{{/entityFields}}
        );
        
        when(applicationService.findById(anyString())).thenReturn(response);
        // TTB-001 FIX: Configure assembler mock to return EntityModel
        when(assembler.toModel(any({{Entity}}Response.class)))
            .thenReturn(EntityModel.of(response));

        // When/Then
        mockMvc.perform(get(BASE_URL + "/{id}", id)
                .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isOk());
        
        verify(applicationService).findById(anyString());
        verify(assembler).toModel(any({{Entity}}Response.class));
    }

    @Test
    @DisplayName("GET /{id} - should return 404 when not found")
    void getById_WhenNotExists_Returns404() throws Exception {
        // Given
        String id = UUID.randomUUID().toString();
        when(applicationService.findById(anyString()))
            .thenThrow(new {{Entity}}NotFoundException({{Entity}}Id.of(id)));

        // When/Then
        mockMvc.perform(get(BASE_URL + "/{id}", id)
                .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isNotFound());
    }

    @Test
    @DisplayName("POST - should create entity and return 201")
    void create_WithValidRequest_ReturnsCreated() throws Exception {
        // Given
        String generatedId = UUID.randomUUID().toString();
        {{Entity}}Response response = new {{Entity}}Response(
            generatedId
            {{#entityFields}}, {{testValue}}{{/entityFields}}
        );
        
        when(applicationService.create(any())).thenReturn(response);
        // TTB-001 FIX: Configure assembler mock
        when(assembler.toModel(any({{Entity}}Response.class)))
            .thenReturn(EntityModel.of(response));

        // When/Then
        mockMvc.perform(post(BASE_URL)
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))  // Simplified for template
            .andExpect(status().isCreated());
        
        verify(applicationService).create(any());
    }
}
