// Template: RetryTest.java.tpl
// Output: {{basePackagePath}}/application/service/{{Service}}ApplicationServiceTest.java
// Purpose: Unit test for retry behavior

package {{basePackage}}.application.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.net.ConnectException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{Service}}ApplicationService retry behavior.
 * 
 * Generated by: mod-002-retry-java-resilience4j
 * ERI Reference: eri-code-009-retry-java-resilience4j
 */
@ExtendWith(MockitoExtension.class)
class {{Service}}ApplicationServiceTest {
    
    @Mock
    private {{ExternalClient}} client;
    
    @InjectMocks
    private {{Service}}ApplicationService service;
    
    @Test
    void {{methodName}}_successOnFirstAttempt() {
        // Arrange
        {{ReturnType}} expected = {{expectedValue}};
        when(client.{{clientMethod}}({{testParam}})).thenReturn(expected);
        
        // Act
        {{ReturnType}} result = service.{{methodName}}({{testParam}});
        
        // Assert
        assertEquals(expected, result);
        verify(client, times(1)).{{clientMethod}}({{testParam}});
    }
    
    @Test
    void {{methodName}}_successAfterRetry() {
        // Arrange
        {{ReturnType}} expected = {{expectedValue}};
        when(client.{{clientMethod}}({{testParam}}))
            .thenThrow(new ConnectException("Connection refused"))
            .thenReturn(expected);
        
        // Act
        {{ReturnType}} result = service.{{methodName}}({{testParam}});
        
        // Assert
        assertEquals(expected, result);
        verify(client, times(2)).{{clientMethod}}({{testParam}});
    }
    
    @Test
    void {{methodName}}_failsAfterMaxRetries() {
        // Arrange
        when(client.{{clientMethod}}({{testParam}}))
            .thenThrow(new ConnectException("Connection refused"));
        
        // Act & Assert
        assertThrows(ConnectException.class, 
            () -> service.{{methodName}}({{testParam}}));
        verify(client, times({{maxAttempts}})).{{clientMethod}}({{testParam}});
    }
}
