// Template: PersistenceAdapter.java.tpl
// Output: {{basePackage}}/adapter/persistence/{{Entity}}PersistenceAdapter.java
// Purpose: Adapter implementing domain repository port via JPA

package {{basePackage}}.adapter.persistence;

import {{basePackage}}.adapter.persistence.entity.{{Entity}}JpaEntity;
import {{basePackage}}.adapter.persistence.mapper.{{Entity}}PersistenceMapper;
import {{basePackage}}.adapter.persistence.repository.{{Entity}}JpaRepository;
import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.model.{{Entity}}Id;
import {{basePackage}}.domain.repository.{{Entity}}Repository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Optional;

/**
 * Persistence adapter implementing {{Entity}}Repository port.
 * Uses JPA for database access.
 * 
 * Generated by: mod-016-persistence-jpa-spring
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Component
@RequiredArgsConstructor
public class {{Entity}}PersistenceAdapter implements {{Entity}}Repository {
    
    private final {{Entity}}JpaRepository jpaRepository;
    private final {{Entity}}PersistenceMapper mapper;
    
    @Override
    public Optional<{{Entity}}> findById({{Entity}}Id id) {
        return jpaRepository.findById(id.value())
            .map(mapper::toDomain);
    }
    
    @Override
    public List<{{Entity}}> findAll() {
        return jpaRepository.findAll().stream()
            .map(mapper::toDomain)
            .toList();
    }
    
    @Override
    public {{Entity}} save({{Entity}} entity) {
        {{Entity}}JpaEntity jpaEntity = mapper.toJpaEntity(entity);
        {{Entity}}JpaEntity saved = jpaRepository.save(jpaEntity);
        return mapper.toDomain(saved);
    }
    
    @Override
    public void deleteById({{Entity}}Id id) {
        jpaRepository.deleteById(id.value());
    }
}
