// Template: feign-config.java.tpl
// Output: {{basePackage}}/adapter/integration/client/{{ApiName}}ClientConfig.java
// Purpose: Feign client configuration with correlation headers
// Variant: feign

package {{basePackage}}.adapter.integration.client;

import feign.RequestInterceptor;
import org.slf4j.MDC;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Feign configuration for {{ApiName}} client.
 * Adds correlation headers for distributed tracing.
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (feign variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@Configuration
public class {{ApiName}}ClientConfig {
    
    @Bean
    public RequestInterceptor correlationInterceptor() {
        return template -> {
            String correlationId = MDC.get("correlationId");
            if (correlationId != null) {
                template.header("X-Correlation-ID", correlationId);
            }
            template.header("X-Source-System", "{{serviceName}}");
        };
    }
}
