// ═══════════════════════════════════════════════════════════════════════════════
// Template: restclient-config.java.tpl
// Module: mod-code-018-api-integration-rest-java-spring
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackage}}/infrastructure/config/RestClientConfig.java
// Purpose: RestClient bean configuration with timeout support
// ═══════════════════════════════════════════════════════════════════════════════
// REQUIRED VARIABLES: {{api-name}} {{basePackage}} 
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}}.infrastructure.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.client.ClientHttpRequestFactory;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.web.client.RestClient;

import java.time.Duration;

/**
 * RestClient configuration with timeout settings.
 * 
 * Timeouts are configured via application properties:
 * - integration.{{api-name}}.connect-timeout: Connection timeout
 * - integration.{{api-name}}.read-timeout: Read timeout
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (restclient variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@Configuration
public class RestClientConfig {
    
    @Value("${integration.{{api-name}}.connect-timeout:5s}")
    private Duration connectTimeout;
    
    @Value("${integration.{{api-name}}.read-timeout:10s}")
    private Duration readTimeout;
    
    @Bean
    public RestClient.Builder restClientBuilder() {
        return RestClient.builder()
            .requestFactory(clientHttpRequestFactory());
    }
    
    @Bean
    public ClientHttpRequestFactory clientHttpRequestFactory() {
        SimpleClientHttpRequestFactory factory = new SimpleClientHttpRequestFactory();
        factory.setConnectTimeout(connectTimeout);
        factory.setReadTimeout(readTimeout);
        return factory;
    }
}
