// Template: resttemplate-config.java.tpl
// Output: {{basePackage}}/infrastructure/config/RestTemplateConfig.java
// Purpose: RestTemplate bean configuration
// Variant: resttemplate

package {{basePackage}}.infrastructure.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.client.RestTemplate;

/**
 * RestTemplate configuration.
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (resttemplate variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@Configuration
public class RestTemplateConfig {
    
    @Bean
    public RestTemplate restTemplate() {
        return new RestTemplate();
    }
}
