// ═══════════════════════════════════════════════════════════════════════════════
// Template: RestController.java.tpl
// Module: mod-code-015-hexagonal-base-java-spring
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackage}}/adapter/rest/{{Entity}}Controller.java
// Purpose: REST adapter (inbound)
// ═══════════════════════════════════════════════════════════════════════════════
// REQUIRED VARIABLES: {{Entity}} {{basePackage}} {{entityPlural}} 
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}}.adapter.rest;

import {{basePackage}}.application.service.{{Entity}}ApplicationService;
import {{basePackage}}.application.dto.*;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST controller for {{Entity}}.
 * 
 * This is an INBOUND adapter - receives HTTP requests.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
@RestController
@RequestMapping("/api/v1/{{entityPlural}}")
@RequiredArgsConstructor
public class {{Entity}}Controller {
    
    private final {{Entity}}ApplicationService applicationService;
    
    @GetMapping("/{id}")
    public ResponseEntity<{{Entity}}Response> get{{Entity}}(@PathVariable String id) {
        return ResponseEntity.ok(applicationService.get{{Entity}}(id));
    }
    
    @GetMapping
    public ResponseEntity<List<{{Entity}}Response>> getAll{{Entity}}s() {
        return ResponseEntity.ok(applicationService.getAll{{Entity}}s());
    }
    
    @PostMapping
    public ResponseEntity<{{Entity}}Response> create{{Entity}}(
            @Valid @RequestBody Create{{Entity}}Request request) {
        {{Entity}}Response response = applicationService.create{{Entity}}(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }
    
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete{{Entity}}(@PathVariable String id) {
        applicationService.delete{{Entity}}(id);
        return ResponseEntity.noContent().build();
    }
}
