// ═══════════════════════════════════════════════════════════════════════════════
// Template: ApplicationService.java.tpl
// Module: mod-code-015-hexagonal-base-java-spring
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackage}}/application/service/{{Entity}}ApplicationService.java
// Purpose: Application service (orchestration, transactions)
// ═══════════════════════════════════════════════════════════════════════════════
// REQUIRED VARIABLES: {{Entity}} {{^last}} {{basePackage}} {{entity}} {{fieldNamePascal}} {{fieldName}} 
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}}.application.service;

import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.model.{{Entity}}Id;
import {{basePackage}}.domain.service.{{Entity}}DomainService;
import {{basePackage}}.application.dto.*;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
// TB-002 FIX: @Transactional removed - only needed with JPA persistence
// If using mod-016-persistence-jpa, add: import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Application service for {{Entity}}.
 * 
 * Responsibilities:
 * - Transaction management (@Transactional)
 * - DTO conversion
 * - Orchestration of domain services
 * - Cross-cutting concerns (logging, etc.)
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
@Service
@RequiredArgsConstructor
@Slf4j
// TB-002 FIX: @Transactional removed - add via transformation for JPA
public class {{Entity}}ApplicationService {
    
    private final {{Entity}}DomainService domainService;
    
    public {{Entity}}Response get{{Entity}}(String id) {
        log.debug("Getting {{entity}} with id: {}", id);
        {{Entity}} entity = domainService.get{{Entity}}({{Entity}}Id.of(id));
        return toResponse(entity);
    }
    
    public List<{{Entity}}Response> getAll{{Entity}}s() {
        log.debug("Getting all {{entity}}s");
        return domainService.getAll{{Entity}}s().stream()
            .map(this::toResponse)
            .toList();
    }
    
    public {{Entity}}Response create{{Entity}}(Create{{Entity}}Request request) {
        log.debug("Creating {{entity}}: {}", request);
        {{Entity}} entity = domainService.create{{Entity}}(
{{#entityFields}}
            request.{{fieldName}}(){{^last}},{{/last}}
{{/entityFields}}
        );
        return toResponse(entity);
    }
    
    public void delete{{Entity}}(String id) {
        log.debug("Deleting {{entity}} with id: {}", id);
        domainService.delete{{Entity}}({{Entity}}Id.of(id));
    }
    
    private {{Entity}}Response toResponse({{Entity}} entity) {
        return new {{Entity}}Response(
            entity.getId().value(){{#entityFields}},
            entity.get{{fieldNamePascal}}(){{/entityFields}}
        );
    }
}
