// Template: SystemApiUnavailableException.java.tpl
// Output: {{basePackage}}/adapter/systemapi/SystemApiUnavailableException.java
// Purpose: Exception for System API unavailability (circuit breaker open)

package {{basePackage}}.adapter.systemapi;

/**
 * Exception thrown when System API is unavailable.
 * Typically thrown by circuit breaker fallback methods.
 * 
 * Generated by: mod-017-persistence-systemapi
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
public class SystemApiUnavailableException extends RuntimeException {
    
    public SystemApiUnavailableException(String message) {
        super(message);
    }
    
    public SystemApiUnavailableException(String message, Throwable cause) {
        super(message, cause);
    }
}
