// Template: ApplicationConfig.java.tpl
// Output: {{basePackage}}/infrastructure/config/ApplicationConfig.java
// Purpose: Configuration for wiring domain beans

package {{basePackage}}.infrastructure.config;

import {{basePackage}}.domain.repository.{{Entity}}Repository;
import {{basePackage}}.domain.service.{{Entity}}DomainService;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Configuration for wiring domain layer beans.
 * 
 * Domain services are POJOs - we instantiate them here via @Bean.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
@Configuration
public class ApplicationConfig {
    
    @Bean
    public {{Entity}}DomainService {{entity}}DomainService({{Entity}}Repository repository) {
        return new {{Entity}}DomainService(repository);
    }
}
