package {{basePackage}}.infrastructure;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.MDC;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.UUID;

/**
 * Filter to extract or generate correlation ID for request tracing.
 * 
 * Extracts X-Correlation-ID from incoming request header.
 * If not present, generates a new UUID.
 * Adds to MDC for logging and response header for client.
 * 
 * Generated by: skill-code-020-generate-microservice-java-spring
 * Module: mod-015-hexagonal-base-java-spring
 */
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class CorrelationIdFilter extends OncePerRequestFilter {
    
    public static final String CORRELATION_ID_HEADER = "X-Correlation-ID";
    public static final String CORRELATION_ID_MDC_KEY = "correlationId";
    
    @Override
    protected void doFilterInternal(
            HttpServletRequest request,
            HttpServletResponse response,
            FilterChain filterChain) throws ServletException, IOException {
        
        try {
            String correlationId = extractOrGenerate(request);
            MDC.put(CORRELATION_ID_MDC_KEY, correlationId);
            response.addHeader(CORRELATION_ID_HEADER, correlationId);
            
            filterChain.doFilter(request, response);
        } finally {
            MDC.remove(CORRELATION_ID_MDC_KEY);
        }
    }
    
    private String extractOrGenerate(HttpServletRequest request) {
        String correlationId = request.getHeader(CORRELATION_ID_HEADER);
        if (correlationId == null || correlationId.isBlank()) {
            correlationId = UUID.randomUUID().toString();
        }
        return correlationId;
    }
    
    /**
     * Get current correlation ID from MDC.
     * Useful for propagating to outbound calls.
     */
    public static String getCurrentCorrelationId() {
        String id = MDC.get(CORRELATION_ID_MDC_KEY);
        return id != null ? id : UUID.randomUUID().toString();
    }
}
