// Template: feign-config.java.tpl
// Output: {{basePackage}}/adapter/systemapi/client/{{Entity}}SystemApiFeignConfig.java
// Purpose: Feign client configuration with headers and interceptors
// Variant: feign (only generated when using Feign)

package {{basePackage}}.adapter.systemapi.client;

import feign.RequestInterceptor;
import org.slf4j.MDC;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Feign configuration for {{Entity}} System API client.
 * Adds correlation headers for traceability.
 * 
 * Generated by: mod-017-persistence-systemapi (feign variant)
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Configuration
public class {{Entity}}SystemApiFeignConfig {
    
    @Bean
    public RequestInterceptor correlationIdInterceptor() {
        return requestTemplate -> {
            String correlationId = MDC.get("correlationId");
            if (correlationId != null) {
                requestTemplate.header("X-Correlation-ID", correlationId);
            }
            requestTemplate.header("X-Source-System", "{{serviceName}}");
        };
    }
}
