// Template: Entity.java.tpl
// Output: {{basePackage}}/domain/model/{{Entity}}.java
// Purpose: Domain entity (pure POJO, NO framework annotations)

package {{basePackage}}.domain.model;

{{#entityImports}}
import {{.}};
{{/entityImports}}
import java.util.UUID;

/**
 * {{Entity}} domain entity.
 * 
 * IMPORTANT: This is a pure domain object.
 * - NO Spring annotations (@Entity, @Component, etc.)
 * - NO JPA annotations
 * - Business logic belongs here
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public class {{Entity}} {
    
    private final {{Entity}}Id id;
{{#entityFields}}
    private {{fieldType}} {{fieldName}};
{{/entityFields}}
    
    // Factory method for new entities
    public static {{Entity}} create({{#entityFields}}{{fieldType}} {{fieldName}}{{^last}}, {{/last}}{{/entityFields}}) {
        {{Entity}} entity = new {{Entity}}();
        entity.id = {{Entity}}Id.generate();
{{#entityFields}}
        entity.{{fieldName}} = {{fieldName}};
{{/entityFields}}
        return entity;
    }
    
    // Factory method for reconstitution from persistence
    public static {{Entity}} reconstitute({{Entity}}Id id{{#entityFields}}, {{fieldType}} {{fieldName}}{{/entityFields}}) {
        {{Entity}} entity = new {{Entity}}();
        entity.id = id;
{{#entityFields}}
        entity.{{fieldName}} = {{fieldName}};
{{/entityFields}}
        return entity;
    }
    
    private {{Entity}}() {}
    
    public {{Entity}}Id getId() {
        return id;
    }
    
{{#entityFields}}
    public {{fieldType}} get{{fieldNamePascal}}() {
        return {{fieldName}};
    }
    
{{/entityFields}}
    // Domain behavior methods go here
}
