// Template: EntityId.java.tpl
// Output: {{basePackage}}/domain/model/{{Entity}}Id.java
// Purpose: Value object for entity ID (type safety)

package {{basePackage}}.domain.model;

import java.util.UUID;

/**
 * Value object for {{Entity}} identifier.
 * Provides type safety - prevents passing wrong ID type.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public record {{Entity}}Id(String value) {
    
    public {{Entity}}Id {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("{{Entity}}Id cannot be null or blank");
        }
    }
    
    public static {{Entity}}Id generate() {
        return new {{Entity}}Id(UUID.randomUUID().toString());
    }
    
    public static {{Entity}}Id of(String value) {
        return new {{Entity}}Id(value);
    }
    
    @Override
    public String toString() {
        return value;
    }
}
