// Template: Repository.java.tpl
// Output: {{basePackage}}/domain/repository/{{Entity}}Repository.java
// Purpose: Repository port (interface in domain layer)

package {{basePackage}}.domain.repository;

import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.model.{{Entity}}Id;

import java.util.List;
import java.util.Optional;

/**
 * Repository port for {{Entity}} persistence.
 * 
 * IMPORTANT: This is a PORT (interface) in the domain layer.
 * - NO Spring annotations
 * - NO implementation details
 * - Implementations live in adapter layer
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public interface {{Entity}}Repository {
    
    Optional<{{Entity}}> findById({{Entity}}Id id);
    
    List<{{Entity}}> findAll();
    
    {{Entity}} save({{Entity}} entity);
    
    void deleteById({{Entity}}Id id);
}
