// Template: SystemApiAdapterTest.java.tpl
// Output: {{basePackagePath}}/adapter/out/systemapi/{{Entity}}SystemApiAdapterTest.java
// Purpose: Unit test for System API adapter

package {{basePackage}}.adapter.out.systemapi;

import {{basePackage}}.adapter.out.systemapi.client.{{Entity}}SystemApiClient;
import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiRequest;
import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiResponse;
import {{basePackage}}.adapter.out.systemapi.mapper.{{Entity}}SystemApiMapper;
import {{basePackage}}.domain.model.{{Entity}};

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{Entity}}SystemApiAdapter.
 * 
 * Tests adapter logic with mocked client and mapper.
 * Resilience behavior (circuit breaker, retry) tested separately
 * with integration tests.
 * 
 * Generated by: mod-017-persistence-systemapi
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@ExtendWith(MockitoExtension.class)
class {{Entity}}SystemApiAdapterTest {
    
    @Mock
    private {{Entity}}SystemApiClient client;
    
    @Mock
    private {{Entity}}SystemApiMapper mapper;
    
    private {{Entity}}SystemApiAdapter adapter;
    
    @BeforeEach
    void setUp() {
        adapter = new {{Entity}}SystemApiAdapter(client, mapper);
    }
    
    @Test
    void findById_WhenExists_ReturnsMappedEntity() {
        // Given
        String id = "123";
        {{Entity}}SystemApiResponse dto = {{Entity}}SystemApiResponse.builder().id(id).build();
        {{Entity}} entity = {{Entity}}.builder().id(id).build();
        
        when(client.getById(id)).thenReturn(dto);
        when(mapper.toDomain(dto)).thenReturn(entity);
        
        // When
        Optional<{{Entity}}> result = adapter.findById(id);
        
        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getId()).isEqualTo(id);
        verify(client).getById(id);
        verify(mapper).toDomain(dto);
    }
    
    @Test
    void findById_WhenNotExists_ReturnsEmpty() {
        // Given
        String id = "non-existent";
        when(client.getById(id)).thenReturn(null);
        when(mapper.toDomain(null)).thenReturn(null);
        
        // When
        Optional<{{Entity}}> result = adapter.findById(id);
        
        // Then
        assertThat(result).isEmpty();
    }
    
    @Test
    void findAll_ReturnsMappedEntities() {
        // Given
        {{Entity}}SystemApiResponse dto1 = {{Entity}}SystemApiResponse.builder().id("1").build();
        {{Entity}}SystemApiResponse dto2 = {{Entity}}SystemApiResponse.builder().id("2").build();
        {{Entity}} entity1 = {{Entity}}.builder().id("1").build();
        {{Entity}} entity2 = {{Entity}}.builder().id("2").build();
        
        when(client.getAll()).thenReturn(List.of(dto1, dto2));
        when(mapper.toDomain(dto1)).thenReturn(entity1);
        when(mapper.toDomain(dto2)).thenReturn(entity2);
        
        // When
        List<{{Entity}}> result = adapter.findAll();
        
        // Then
        assertThat(result).hasSize(2);
        assertThat(result).extracting({{Entity}}::getId).containsExactly("1", "2");
    }
    
    @Test
    void save_ReturnsMappedSavedEntity() {
        // Given
        {{Entity}} entity = {{Entity}}.builder().id("123").build();
        {{Entity}}SystemApiRequest inputDto = {{Entity}}SystemApiRequest.builder().id("123").build();
        {{Entity}}SystemApiResponse savedDto = {{Entity}}SystemApiResponse.builder().id("123").build();
        {{Entity}} savedEntity = {{Entity}}.builder().id("123").build();
        
        when(mapper.toRequest(entity)).thenReturn(inputDto);
        when(client.save(inputDto)).thenReturn(savedDto);
        when(mapper.toDomain(savedDto)).thenReturn(savedEntity);
        
        // When
        {{Entity}} result = adapter.save(entity);
        
        // Then
        assertThat(result).isNotNull();
        assertThat(result.getId()).isEqualTo("123");
        verify(client).save(inputDto);
    }
    
    @Test
    void deleteById_CallsClient() {
        // Given
        String id = "123";
        
        // When
        adapter.deleteById(id);
        
        // Then
        verify(client).deleteById(id);
    }
    
    // TTB-002 FIX: Added test for System API error response codes
    @Test
    void findById_WhenSystemReturnsError_ReturnsEmpty() {
        // Given - System API returns response but with error code
        String id = "123";
        {{Entity}}SystemApiResponse errorDto = {{Entity}}SystemApiResponse.builder()
            .id(id)
            .sysRc("99")  // Error code
            .sysMsg("Record not found")
            .build();
        
        when(client.getById(id)).thenReturn(errorDto);
        
        // When
        Optional<{{Entity}}> result = adapter.findById(id);
        
        // Then
        assertThat(result).isEmpty();
        verify(mapper, never()).toDomain(any());  // Should not map error response
    }
}
