// Template: RateLimiterTest.java.tpl
// Output: {{basePackagePath}}/application/service/{{Service}}ApplicationServiceTest.java
// Purpose: Unit test for rate limiter behavior

package {{basePackage}}.application.service;

import io.github.resilience4j.ratelimiter.RequestNotPermitted;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{Service}}ApplicationService rate limiter behavior.
 * 
 * Generated by: mod-004-rate-limiter-java-resilience4j
 * ERI Reference: eri-code-011-rate-limiter-java-resilience4j
 */
@ExtendWith(MockitoExtension.class)
class {{Service}}ApplicationServiceTest {
    
    @Mock
    private {{ExternalClient}} client;
    
    @InjectMocks
    private {{Service}}ApplicationService service;
    
    @Test
    void {{methodName}}_withinRateLimit_succeeds() {
        // Arrange
        {{ReturnType}} expected = {{expectedValue}};
        when(client.{{clientMethod}}({{testParam}})).thenReturn(expected);
        
        // Act
        {{ReturnType}} result = service.{{methodName}}({{testParam}});
        
        // Assert
        assertEquals(expected, result);
        verify(client).{{clientMethod}}({{testParam}});
    }
    
    @Test
    void {{methodName}}_exceedsRateLimit_throwsException() {
        // Arrange
        {{ReturnType}} expected = {{expectedValue}};
        when(client.{{clientMethod}}({{testParam}})).thenReturn(expected);
        
        // Act - call more times than rate limit allows
        for (int i = 0; i < {{limitForPeriod}} + 1; i++) {
            try {
                service.{{methodName}}({{testParam}});
            } catch (RequestNotPermitted e) {
                // Expected after limit exceeded
                return;
            }
        }
        
        // Assert - should have thrown by now
        fail("Expected RequestNotPermitted exception");
    }
}
