// Template: JpaRepository.java.tpl
// Output: {{basePackage}}/adapter/persistence/repository/{{Entity}}JpaRepository.java
// Purpose: Spring Data JPA repository (adapter implementation detail)

package {{basePackage}}.adapter.persistence.repository;

import {{basePackage}}.adapter.persistence.entity.{{Entity}}JpaEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for {{Entity}}.
 * 
 * This is an implementation detail of the adapter layer.
 * Domain layer does NOT depend on this.
 * 
 * Generated by: mod-016-persistence-jpa-spring
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Repository
public interface {{Entity}}JpaRepository extends JpaRepository<{{Entity}}JpaEntity, String> {
    // Add custom query methods as needed
}
