package {{basePackage}}.application.dto;

import jakarta.validation.constraints.*;

/**
 * Request DTO for updating an existing {{Entity}}.
 * 
 * Generated by: skill-code-020-generate-microservice-java-spring
 * Module: mod-015-hexagonal-base-java-spring
 */
public record Update{{Entity}}Request(
    {{#updateableFields}}
    {{#if validation.maxLength}}
    @Size(max = {{validation.maxLength}}, message = "{{fieldName}} must not exceed {{validation.maxLength}} characters")
    {{/if}}
    {{#if validation.email}}
    @Email(message = "{{fieldName}} must be a valid email address")
    {{/if}}
    {{type}} {{fieldName}}{{#unless @last}},{{/unless}}
    {{/updateableFields}}
) {
    
    /**
     * Check if any field is non-null (partial update).
     */
    public boolean hasUpdates() {
        return {{#updateableFields}}{{fieldName}} != null{{#unless @last}} || {{/unless}}{{/updateableFields}};
    }
}
