// Template: SystemApiMapper.java.tpl
// Output: {{basePackage}}/adapter/systemapi/mapper/{{Entity}}SystemApiMapper.java
// Purpose: Maps between domain entities and System API DTOs

package {{basePackage}}.adapter.systemapi.mapper;

import {{basePackage}}.adapter.systemapi.dto.{{Entity}}Dto;
import {{basePackage}}.domain.model.{{Entity}};
import org.springframework.stereotype.Component;

/**
 * Mapper between {{Entity}} domain model and System API DTO.
 * 
 * Generated by: mod-017-persistence-systemapi
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Component
public class {{Entity}}SystemApiMapper {
    
    /**
     * Maps System API DTO to domain entity.
     */
    public {{Entity}} toDomain({{Entity}}Dto dto) {
        if (dto == null) {
            return null;
        }
        
        return {{Entity}}.builder()
            .id(dto.getId())
{{#fields}}
            .{{name}}(dto.get{{NamePascal}}())
{{/fields}}
            .build();
    }
    
    /**
     * Maps domain entity to System API DTO.
     */
    public {{Entity}}Dto toDto({{Entity}} entity) {
        if (entity == null) {
            return null;
        }
        
        return {{Entity}}Dto.builder()
            .id(entity.getId())
{{#fields}}
            .{{name}}(entity.get{{NamePascal}}())
{{/fields}}
            .build();
    }
}
