// Template: Dto.java.tpl
// Output: {{basePackage}}/adapter/systemapi/dto/{{Entity}}Dto.java
// Purpose: Data Transfer Object for System API communication

package {{basePackage}}.adapter.systemapi.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.extern.jackson.Jacksonized;

/**
 * DTO for {{Entity}} System API communication.
 * Maps to external system contract.
 * 
 * Generated by: mod-017-persistence-systemapi
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Data
@Builder
@Jacksonized
public class {{Entity}}Dto {
    
    @JsonProperty("{{idJsonField}}")
    private String id;
    
{{#fields}}
    @JsonProperty("{{jsonField}}")
    private {{type}} {{name}};
    
{{/fields}}
}
