// Template: feign.java.tpl
// Output: {{basePackage}}/adapter/out/systemapi/client/{{Entity}}SystemApiClient.java
// Purpose: Feign client for System API communication
// Variant: feign

package {{basePackage}}.adapter.out.systemapi.client;

import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiRequest;
import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiResponse;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Feign client for {{Entity}} System API.
 * 
 * Recommended for:
 * - Declarative HTTP client definition
 * - Built-in Resilience4j integration
 * - Easy testing with mocks
 * 
 * Generated by: mod-017-persistence-systemapi (feign variant)
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@FeignClient(
    name = "{{serviceName}}-systemapi",
    url = "${system-api.{{serviceName}}.base-url}",
    configuration = {{Entity}}SystemApiFeignConfig.class
)
public interface {{Entity}}SystemApiClient {
    
    @GetMapping("{{resourcePath}}/{id}")
    {{Entity}}SystemApiResponse getById(@PathVariable("id") String id);
    
    @GetMapping("{{resourcePath}}")
    List<{{Entity}}SystemApiResponse> getAll();
    
    @PostMapping("{{resourcePath}}")
    {{Entity}}SystemApiResponse save(@RequestBody {{Entity}}SystemApiRequest request);
    
    @DeleteMapping("{{resourcePath}}/{id}")
    void deleteById(@PathVariable("id") String id);
}
