// Template: resttemplate.java.tpl
// Output: {{basePackage}}/adapter/out/systemapi/client/{{Entity}}SystemApiClient.java
// Purpose: RestTemplate client for System API communication
// Variant: resttemplate

package {{basePackage}}.adapter.out.systemapi.client;

import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiRequest;
import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiResponse;
import lombok.RequiredArgsConstructor;
import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.*;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

import java.util.List;

/**
 * RestTemplate client for {{Entity}} System API.
 * 
 * Recommended for:
 * - Legacy Spring Boot versions
 * - When imperative style is preferred
 * - Complex request customization
 * 
 * Generated by: mod-017-persistence-systemapi (resttemplate variant)
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Component
@RequiredArgsConstructor
public class {{Entity}}SystemApiClient {
    
    private final RestTemplate restTemplate;
    
    @Value("${system-api.{{serviceName}}.base-url}")
    private String baseUrl;
    
    private static final String RESOURCE_PATH = "{{resourcePath}}";
    
    public {{Entity}}SystemApiResponse getById(String id) {
        String url = baseUrl + RESOURCE_PATH + "/" + id;
        HttpEntity<Void> entity = new HttpEntity<>(createHeaders());
        
        ResponseEntity<{{Entity}}SystemApiResponse> response = restTemplate.exchange(
            url,
            HttpMethod.GET,
            entity,
            {{Entity}}SystemApiResponse.class
        );
        
        return response.getBody();
    }
    
    public List<{{Entity}}SystemApiResponse> getAll() {
        String url = baseUrl + RESOURCE_PATH;
        HttpEntity<Void> entity = new HttpEntity<>(createHeaders());
        
        ResponseEntity<List<{{Entity}}SystemApiResponse>> response = restTemplate.exchange(
            url,
            HttpMethod.GET,
            entity,
            new ParameterizedTypeReference<>() {}
        );
        
        return response.getBody();
    }
    
    public {{Entity}}SystemApiResponse save({{Entity}}SystemApiRequest request) {
        String url = baseUrl + RESOURCE_PATH;
        HttpEntity<{{Entity}}SystemApiRequest> entity = new HttpEntity<>(request, createHeaders());
        
        ResponseEntity<{{Entity}}SystemApiResponse> response = restTemplate.exchange(
            url,
            HttpMethod.POST,
            entity,
            {{Entity}}SystemApiResponse.class
        );
        
        return response.getBody();
    }
    
    public void deleteById(String id) {
        String url = baseUrl + RESOURCE_PATH + "/" + id;
        HttpEntity<Void> entity = new HttpEntity<>(createHeaders());
        
        restTemplate.exchange(
            url,
            HttpMethod.DELETE,
            entity,
            Void.class
        );
    }
    
    /**
     * Creates HTTP headers with correlation ID for traceability.
     */
    private HttpHeaders createHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        
        String correlationId = MDC.get("correlationId");
        if (correlationId != null) {
            headers.set("X-Correlation-ID", correlationId);
        }
        headers.set("X-Source-System", "{{serviceName}}");
        
        return headers;
    }
}
