// Template: restclient.java.tpl
// Output: {{basePackage}}/adapter/out/systemapi/client/{{Entity}}SystemApiClient.java
// Purpose: RestClient (Spring 6.1+) for System API communication
// Variant: restclient

package {{basePackage}}.adapter.out.systemapi.client;

import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiRequest;
import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiResponse;
import lombok.RequiredArgsConstructor;
import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

import java.util.List;

/**
 * RestClient (Spring 6.1+) for {{Entity}} System API.
 * 
 * Recommended for:
 * - Spring Boot 3.2+ / Spring 6.1+
 * - Modern fluent API
 * - New projects
 * 
 * Generated by: mod-017-persistence-systemapi (restclient variant)
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Component
@RequiredArgsConstructor
public class {{Entity}}SystemApiClient {
    
    private final RestClient restClient;
    
    @Value("${system-api.{{serviceName}}.base-url}")
    private String baseUrl;
    
    private static final String RESOURCE_PATH = "{{resourcePath}}";
    
    public {{Entity}}SystemApiResponse getById(String id) {
        return restClient.get()
            .uri(baseUrl + RESOURCE_PATH + "/{id}", id)
            .headers(this::addCorrelationHeaders)
            .retrieve()
            .body({{Entity}}SystemApiResponse.class);
    }
    
    public List<{{Entity}}SystemApiResponse> getAll() {
        return restClient.get()
            .uri(baseUrl + RESOURCE_PATH)
            .headers(this::addCorrelationHeaders)
            .retrieve()
            .body(new ParameterizedTypeReference<>() {});
    }
    
    public {{Entity}}SystemApiResponse save({{Entity}}SystemApiRequest request) {
        return restClient.post()
            .uri(baseUrl + RESOURCE_PATH)
            .headers(this::addCorrelationHeaders)
            .contentType(MediaType.APPLICATION_JSON)
            .body(request)
            .retrieve()
            .body({{Entity}}SystemApiResponse.class);
    }
    
    public void deleteById(String id) {
        restClient.delete()
            .uri(baseUrl + RESOURCE_PATH + "/{id}", id)
            .headers(this::addCorrelationHeaders)
            .retrieve()
            .toBodilessEntity();
    }
    
    /**
     * Adds correlation headers for traceability.
     */
    private void addCorrelationHeaders(org.springframework.http.HttpHeaders headers) {
        String correlationId = MDC.get("correlationId");
        if (correlationId != null) {
            headers.set("X-Correlation-ID", correlationId);
        }
        headers.set("X-Source-System", "{{serviceName}}");
    }
}
