// Template: ControllerTest.java.tpl
// Output: {{basePackagePath}}/infrastructure/adapter/in/rest/{{Entity}}ControllerTest.java
// Purpose: Unit test for REST controller (WebMvcTest, no full context)

package {{basePackage}}.infrastructure.adapter.in.rest;

import {{basePackage}}.application.{{Entity}}ApplicationService;
import {{basePackage}}.application.dto.*;
import {{basePackage}}.domain.model.*;
import {{basePackage}}.domain.exception.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;
import java.util.UUID;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Unit tests for {{Entity}}Controller.
 * 
 * Uses @WebMvcTest for isolated controller testing.
 * Application service is mocked.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
@WebMvcTest({{Entity}}Controller.class)
class {{Entity}}ControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private {{Entity}}ApplicationService applicationService;

    private static final String BASE_URL = "/api/v1/{{entityPlural}}";

    @Test
    @DisplayName("GET /{id} - should return entity when exists")
    void getById_WhenExists_ReturnsEntity() throws Exception {
        // Given
        UUID id = UUID.randomUUID();
        {{Entity}}Response response = {{Entity}}Response.builder()
            .id(id)
            {{#entityFields}}
            .{{name}}({{testValue}})
            {{/entityFields}}
            .build();
        
        when(applicationService.get{{Entity}}(any())).thenReturn(response);

        // When/Then
        mockMvc.perform(get(BASE_URL + "/{id}", id)
                .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.id").value(id.toString()));
        
        verify(applicationService).get{{Entity}}(any());
    }

    @Test
    @DisplayName("GET /{id} - should return 404 when not found")
    void getById_WhenNotExists_Returns404() throws Exception {
        // Given
        UUID id = UUID.randomUUID();
        when(applicationService.get{{Entity}}(any()))
            .thenThrow(new {{Entity}}NotFoundException(id));

        // When/Then
        mockMvc.perform(get(BASE_URL + "/{id}", id)
                .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isNotFound());
    }

    @Test
    @DisplayName("POST - should create entity and return 201")
    void create_WithValidRequest_ReturnsCreated() throws Exception {
        // Given
        Create{{Entity}}Request request = Create{{Entity}}Request.builder()
            {{#entityFields}}
            .{{name}}({{testValue}})
            {{/entityFields}}
            .build();
        
        UUID generatedId = UUID.randomUUID();
        {{Entity}}Response response = {{Entity}}Response.builder()
            .id(generatedId)
            {{#entityFields}}
            .{{name}}({{testValue}})
            {{/entityFields}}
            .build();
        
        when(applicationService.create{{Entity}}(any())).thenReturn(response);

        // When/Then
        mockMvc.perform(post(BASE_URL)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.id").value(generatedId.toString()));
        
        verify(applicationService).create{{Entity}}(any());
    }

    @Test
    @DisplayName("PUT /{id} - should update entity and return 200")
    void update_WhenExists_ReturnsUpdated() throws Exception {
        // Given
        UUID id = UUID.randomUUID();
        Update{{Entity}}Request request = Update{{Entity}}Request.builder()
            {{#entityFields}}
            .{{name}}({{testValue}})
            {{/entityFields}}
            .build();
        
        {{Entity}}Response response = {{Entity}}Response.builder()
            .id(id)
            {{#entityFields}}
            .{{name}}({{testValue}})
            {{/entityFields}}
            .build();
        
        when(applicationService.update{{Entity}}(any(), any())).thenReturn(response);

        // When/Then
        mockMvc.perform(put(BASE_URL + "/{id}", id)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.id").value(id.toString()));
    }

    @Test
    @DisplayName("DELETE /{id} - should delete entity and return 204")
    void delete_WhenExists_ReturnsNoContent() throws Exception {
        // Given
        UUID id = UUID.randomUUID();
        doNothing().when(applicationService).delete{{Entity}}(any());

        // When/Then
        mockMvc.perform(delete(BASE_URL + "/{id}", id)
                .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isNoContent());
        
        verify(applicationService).delete{{Entity}}(any());
    }

    @Test
    @DisplayName("POST - should return 400 for invalid request")
    void create_WithInvalidRequest_ReturnsBadRequest() throws Exception {
        // Given
        String invalidJson = "{}";  // Missing required fields

        // When/Then
        mockMvc.perform(post(BASE_URL)
                .contentType(MediaType.APPLICATION_JSON)
                .content(invalidJson))
            .andExpect(status().isBadRequest());
    }
}
