// Template: EntityTest.java.tpl
// Output: {{basePackagePath}}/domain/model/{{Entity}}Test.java
// Purpose: Unit test for domain entity (factory methods, domain behavior)

package {{basePackage}}.domain.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;

import static org.assertj.core.api.Assertions.*;

/**
 * Unit tests for {{Entity}} domain entity.
 * 
 * Tests:
 * - Factory method creation
 * - Reconstitution from persistence
 * - Domain invariants
 * - Value object equality
 * 
 * NO Spring context needed - pure POJO testing.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
class {{Entity}}Test {

    @Nested
    @DisplayName("Factory Method: create()")
    class CreateTests {
        
        @Test
        @DisplayName("should create entity with generated ID")
        void create_WithValidData_GeneratesId() {
            // When
            {{Entity}} entity = {{Entity}}.create({{#entityFields}}{{testValue}}{{^last}}, {{/last}}{{/entityFields}});
            
            // Then
            assertThat(entity).isNotNull();
            assertThat(entity.getId()).isNotNull();
            assertThat(entity.getId().getValue()).isNotNull();
        }
        
        @Test
        @DisplayName("should set all fields correctly")
        void create_WithValidData_SetsFields() {
            // Given
            {{#entityFields}}
            {{type}} {{name}} = {{testValue}};
            {{/entityFields}}
            
            // When
            {{Entity}} entity = {{Entity}}.create({{#entityFields}}{{name}}{{^last}}, {{/last}}{{/entityFields}});
            
            // Then
            {{#entityFields}}
            assertThat(entity.get{{Name}}()).isEqualTo({{name}});
            {{/entityFields}}
        }
    }
    
    @Nested
    @DisplayName("Factory Method: reconstitute()")
    class ReconstituteTests {
        
        @Test
        @DisplayName("should reconstitute entity with existing ID")
        void reconstitute_WithExistingId_PreservesId() {
            // Given
            {{Entity}}Id existingId = {{Entity}}Id.generate();
            
            // When
            {{Entity}} entity = {{Entity}}.reconstitute(existingId{{#entityFields}}, {{testValue}}{{/entityFields}});
            
            // Then
            assertThat(entity.getId()).isEqualTo(existingId);
        }
        
        @Test
        @DisplayName("should set all fields correctly")
        void reconstitute_WithValidData_SetsFields() {
            // Given
            {{Entity}}Id id = {{Entity}}Id.generate();
            {{#entityFields}}
            {{type}} {{name}} = {{testValue}};
            {{/entityFields}}
            
            // When
            {{Entity}} entity = {{Entity}}.reconstitute(id{{#entityFields}}, {{name}}{{/entityFields}});
            
            // Then
            assertThat(entity.getId()).isEqualTo(id);
            {{#entityFields}}
            assertThat(entity.get{{Name}}()).isEqualTo({{name}});
            {{/entityFields}}
        }
    }
    
    @Nested
    @DisplayName("Domain Behavior")
    class DomainBehaviorTests {
        
        @Test
        @DisplayName("two entities with same ID should be equal")
        void equals_SameId_AreEqual() {
            // Given
            {{Entity}}Id id = {{Entity}}Id.generate();
            {{Entity}} entity1 = {{Entity}}.reconstitute(id{{#entityFields}}, {{testValue}}{{/entityFields}});
            {{Entity}} entity2 = {{Entity}}.reconstitute(id{{#entityFields}}, {{testValue}}{{/entityFields}});
            
            // Then
            assertThat(entity1).isEqualTo(entity2);
            assertThat(entity1.hashCode()).isEqualTo(entity2.hashCode());
        }
        
        @Test
        @DisplayName("two entities with different ID should not be equal")
        void equals_DifferentId_AreNotEqual() {
            // Given
            {{Entity}} entity1 = {{Entity}}.create({{#entityFields}}{{testValue}}{{^last}}, {{/last}}{{/entityFields}});
            {{Entity}} entity2 = {{Entity}}.create({{#entityFields}}{{testValue}}{{^last}}, {{/last}}{{/entityFields}});
            
            // Then
            assertThat(entity1).isNotEqualTo(entity2);
        }
    }
}
