// Template: EntityIdTest.java.tpl
// Output: {{basePackagePath}}/domain/model/{{Entity}}IdTest.java
// Purpose: Unit test for value object ID (creation, equality, validation)

package {{basePackage}}.domain.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;

import java.util.UUID;

import static org.assertj.core.api.Assertions.*;

/**
 * Unit tests for {{Entity}}Id value object.
 * 
 * Tests:
 * - ID generation
 * - ID creation from existing value
 * - Value object equality
 * - Immutability
 * 
 * NO Spring context needed - pure POJO testing.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
class {{Entity}}IdTest {

    @Nested
    @DisplayName("Factory Method: generate()")
    class GenerateTests {
        
        @Test
        @DisplayName("should generate unique ID")
        void generate_CreatesUniqueId() {
            // When
            {{Entity}}Id id1 = {{Entity}}Id.generate();
            {{Entity}}Id id2 = {{Entity}}Id.generate();
            
            // Then
            assertThat(id1).isNotNull();
            assertThat(id2).isNotNull();
            assertThat(id1).isNotEqualTo(id2);
        }
        
        @Test
        @DisplayName("should have non-null value")
        void generate_HasNonNullValue() {
            // When
            {{Entity}}Id id = {{Entity}}Id.generate();
            
            // Then
            assertThat(id.getValue()).isNotNull();
        }
    }
    
    @Nested
    @DisplayName("Factory Method: of()")
    class OfTests {
        
        @Test
        @DisplayName("should create ID from existing UUID")
        void of_WithValidUuid_CreatesId() {
            // Given
            UUID uuid = UUID.randomUUID();
            
            // When
            {{Entity}}Id id = {{Entity}}Id.of(uuid);
            
            // Then
            assertThat(id.getValue()).isEqualTo(uuid);
        }
        
        @Test
        @DisplayName("should reject null UUID")
        void of_WithNullUuid_ThrowsException() {
            // When/Then
            assertThatThrownBy(() -> {{Entity}}Id.of(null))
                .isInstanceOf(IllegalArgumentException.class);
        }
    }
    
    @Nested
    @DisplayName("Factory Method: fromString()")
    class FromStringTests {
        
        @Test
        @DisplayName("should create ID from valid string")
        void fromString_WithValidString_CreatesId() {
            // Given
            UUID uuid = UUID.randomUUID();
            String uuidString = uuid.toString();
            
            // When
            {{Entity}}Id id = {{Entity}}Id.fromString(uuidString);
            
            // Then
            assertThat(id.getValue()).isEqualTo(uuid);
        }
        
        @Test
        @DisplayName("should reject invalid string")
        void fromString_WithInvalidString_ThrowsException() {
            // When/Then
            assertThatThrownBy(() -> {{Entity}}Id.fromString("not-a-uuid"))
                .isInstanceOf(IllegalArgumentException.class);
        }
        
        @Test
        @DisplayName("should reject null string")
        void fromString_WithNullString_ThrowsException() {
            // When/Then
            assertThatThrownBy(() -> {{Entity}}Id.fromString(null))
                .isInstanceOf(IllegalArgumentException.class);
        }
    }
    
    @Nested
    @DisplayName("Value Object Equality")
    class EqualityTests {
        
        @Test
        @DisplayName("two IDs with same value should be equal")
        void equals_SameValue_AreEqual() {
            // Given
            UUID uuid = UUID.randomUUID();
            {{Entity}}Id id1 = {{Entity}}Id.of(uuid);
            {{Entity}}Id id2 = {{Entity}}Id.of(uuid);
            
            // Then
            assertThat(id1).isEqualTo(id2);
            assertThat(id1.hashCode()).isEqualTo(id2.hashCode());
        }
        
        @Test
        @DisplayName("two IDs with different value should not be equal")
        void equals_DifferentValue_AreNotEqual() {
            // Given
            {{Entity}}Id id1 = {{Entity}}Id.generate();
            {{Entity}}Id id2 = {{Entity}}Id.generate();
            
            // Then
            assertThat(id1).isNotEqualTo(id2);
        }
        
        @Test
        @DisplayName("toString should return UUID string")
        void toString_ReturnsUuidString() {
            // Given
            UUID uuid = UUID.randomUUID();
            {{Entity}}Id id = {{Entity}}Id.of(uuid);
            
            // Then
            assertThat(id.toString()).contains(uuid.toString());
        }
    }
}
