// Template: PersistenceAdapterTest.java.tpl
// Output: {{basePackagePath}}/adapter/persistence/{{Entity}}PersistenceAdapterTest.java
// Purpose: Unit test for persistence adapter

package {{basePackage}}.adapter.persistence;

import {{basePackage}}.adapter.persistence.entity.{{Entity}}JpaEntity;
import {{basePackage}}.adapter.persistence.mapper.{{Entity}}PersistenceMapper;
import {{basePackage}}.adapter.persistence.repository.{{Entity}}JpaRepository;
import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.model.{{Entity}}Id;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{Entity}}PersistenceAdapter.
 * 
 * Generated by: mod-016-persistence-jpa-spring
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@ExtendWith(MockitoExtension.class)
class {{Entity}}PersistenceAdapterTest {
    
    @Mock
    private {{Entity}}JpaRepository jpaRepository;
    
    @Mock
    private {{Entity}}PersistenceMapper mapper;
    
    private {{Entity}}PersistenceAdapter adapter;
    
    @BeforeEach
    void setUp() {
        adapter = new {{Entity}}PersistenceAdapter(jpaRepository, mapper);
    }
    
    @Test
    void findById_WhenExists_ReturnsMappedEntity() {
        // Given
        String id = "123";
        {{Entity}}JpaEntity jpaEntity = {{Entity}}JpaEntity.builder().id(id).build();
        {{Entity}} entity = {{Entity}}.reconstitute({{Entity}}Id.of(id){{#entityFields}}, {{testValue}}{{/entityFields}});
        
        when(jpaRepository.findById(id)).thenReturn(Optional.of(jpaEntity));
        when(mapper.toDomain(jpaEntity)).thenReturn(entity);
        
        // When
        Optional<{{Entity}}> result = adapter.findById({{Entity}}Id.of(id));
        
        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getId().value()).isEqualTo(id);
    }
    
    @Test
    void save_MapsSavesAndReturns() {
        // Given
        {{Entity}} entity = {{Entity}}.reconstitute({{Entity}}Id.generate(){{#entityFields}}, {{testValue}}{{/entityFields}});
        {{Entity}}JpaEntity jpaEntity = {{Entity}}JpaEntity.builder().id(entity.getId().value()).build();
        
        when(mapper.toJpaEntity(entity)).thenReturn(jpaEntity);
        when(jpaRepository.save(jpaEntity)).thenReturn(jpaEntity);
        when(mapper.toDomain(jpaEntity)).thenReturn(entity);
        
        // When
        {{Entity}} result = adapter.save(entity);
        
        // Then
        assertThat(result).isNotNull();
        verify(jpaRepository).save(jpaEntity);
    }
}
