// Template: feign.java.tpl
// Output: {{basePackagePath}}/adapter/out/integration/{{ApiName}}Client.java
// Purpose: Feign client interface for REST API integration
// Variant: feign

package {{basePackage}}.adapter.out.integration;

import {{basePackage}}.adapter.out.integration.dto.{{ApiName}}Response;
import {{basePackage}}.adapter.out.integration.dto.{{ApiName}}Request;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Feign client for {{ApiName}}.
 * Declarative HTTP client - interface only, implementation generated.
 * 
 * Recommended for:
 * - Well-defined, stable APIs
 * - Internal modern APIs
 * - When declarative style improves readability
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (feign variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@FeignClient(
    name = "{{apiName}}",
    url = "${integration.{{apiName}}.base-url}",
    configuration = {{ApiName}}ClientConfig.class
)
public interface {{ApiName}}Client {
    
    @GetMapping("{{resourcePath}}/{id}")
    {{ApiName}}Response getById(@PathVariable("id") String id);
    
    @GetMapping("{{resourcePath}}")
    List<{{ApiName}}Response> getAll();
    
    @PostMapping("{{resourcePath}}")
    {{ApiName}}Response create(@RequestBody {{ApiName}}Request request);
    
    @PutMapping("{{resourcePath}}/{id}")
    {{ApiName}}Response update(@PathVariable("id") String id, @RequestBody {{ApiName}}Request request);
    
    @DeleteMapping("{{resourcePath}}/{id}")
    void delete(@PathVariable("id") String id);
}
