// Template: feign.java.tpl
// Output: {{basePackage}}/adapter/integration/client/{{ApiName}}Client.java
// Purpose: Feign client interface for REST API integration
// Variant: feign

package {{basePackage}}.adapter.integration.client;

import {{basePackage}}.adapter.integration.dto.{{Entity}}Dto;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Feign client for {{ApiName}}.
 * Declarative HTTP client - interface only, implementation generated.
 * 
 * Recommended for:
 * - Well-defined, stable APIs
 * - Internal modern APIs
 * - When declarative style improves readability
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (feign variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@FeignClient(
    name = "{{apiName}}",
    url = "${integration.{{apiName}}.base-url}",
    configuration = {{ApiName}}ClientConfig.class
)
public interface {{ApiName}}Client {
    
    @GetMapping("{{resourcePath}}/{id}")
    {{Entity}}Dto getById(@PathVariable("id") String id);
    
    @GetMapping("{{resourcePath}}")
    List<{{Entity}}Dto> getAll();
    
    @PostMapping("{{resourcePath}}")
    {{Entity}}Dto create(@RequestBody {{Entity}}Dto dto);
    
    @PutMapping("{{resourcePath}}/{id}")
    {{Entity}}Dto update(@PathVariable("id") String id, @RequestBody {{Entity}}Dto dto);
    
    @DeleteMapping("{{resourcePath}}/{id}")
    void delete(@PathVariable("id") String id);
}
