// Template: resttemplate.java.tpl
// Output: {{basePackagePath}}/adapter/out/integration/{{ApiName}}Client.java
// Purpose: RestTemplate client for REST API integration
// Variant: resttemplate

package {{basePackage}}.adapter.out.integration;

import {{basePackage}}.adapter.out.integration.dto.{{ApiName}}Response;
import {{basePackage}}.adapter.out.integration.dto.{{ApiName}}Request;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.*;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

import java.util.List;

/**
 * REST client for {{ApiName}} using RestTemplate.
 * Imperative style with explicit request building.
 * 
 * Recommended for:
 * - Legacy Spring Boot versions (< 3.2)
 * - Existing codebases using RestTemplate
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (resttemplate variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class {{ApiName}}Client {
    
    private final RestTemplate restTemplate;
    
    @Value("${integration.{{apiName}}.base-url}")
    private String baseUrl;
    
    public {{ApiName}}Response getById(String id) {
        log.debug("{{ApiName}}: GET {{resourcePath}}/{}", id);
        
        HttpEntity<Void> entity = new HttpEntity<>(createHeaders());
        ResponseEntity<{{ApiName}}Response> response = restTemplate.exchange(
            baseUrl + "{{resourcePath}}/{id}",
            HttpMethod.GET,
            entity,
            {{ApiName}}Response.class,
            id
        );
        return response.getBody();
    }
    
    public List<{{ApiName}}Response> getAll() {
        log.debug("{{ApiName}}: GET {{resourcePath}}");
        
        HttpEntity<Void> entity = new HttpEntity<>(createHeaders());
        ResponseEntity<List<{{ApiName}}Response>> response = restTemplate.exchange(
            baseUrl + "{{resourcePath}}",
            HttpMethod.GET,
            entity,
            new ParameterizedTypeReference<>() {}
        );
        return response.getBody();
    }
    
    public {{ApiName}}Response create({{ApiName}}Request dto) {
        log.debug("{{ApiName}}: POST {{resourcePath}}");
        
        HttpEntity<{{ApiName}}Request> entity = new HttpEntity<>(dto, createHeaders());
        ResponseEntity<{{ApiName}}Response> response = restTemplate.exchange(
            baseUrl + "{{resourcePath}}",
            HttpMethod.POST,
            entity,
            {{ApiName}}Response.class
        );
        return response.getBody();
    }
    
    public {{ApiName}}Response update(String id, {{ApiName}}Request dto) {
        log.debug("{{ApiName}}: PUT {{resourcePath}}/{}");
        
        HttpEntity<{{ApiName}}Request> entity = new HttpEntity<>(dto, createHeaders());
        ResponseEntity<{{ApiName}}Response> response = restTemplate.exchange(
            baseUrl + "{{resourcePath}}/{id}",
            HttpMethod.PUT,
            entity,
            {{ApiName}}Response.class,
            id
        );
        return response.getBody();
    }
    
    public void delete(String id) {
        log.debug("{{ApiName}}: DELETE {{resourcePath}}/{}", id);
        
        HttpEntity<Void> entity = new HttpEntity<>(createHeaders());
        restTemplate.exchange(
            baseUrl + "{{resourcePath}}/{id}",
            HttpMethod.DELETE,
            entity,
            Void.class,
            id
        );
    }
    
    /**
     * Creates HTTP headers with correlation ID for traceability.
     */
    private HttpHeaders createHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        
        String correlationId = MDC.get("correlationId");
        if (correlationId != null) {
            headers.set("X-Correlation-ID", correlationId);
        }
        headers.set("X-Source-System", "{{serviceName}}");
        
        return headers;
    }
}
