// Template: restclient.java.tpl
// Output: {{basePackage}}/adapter/integration/client/{{ApiName}}Client.java
// Purpose: RestClient implementation for REST API integration (Spring 3.2+)
// Variant: restclient (DEFAULT)

package {{basePackage}}.adapter.integration.client;

import {{basePackage}}.adapter.integration.dto.{{Entity}}Dto;
import {{basePackage}}.adapter.integration.exception.IntegrationException;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

import java.util.List;

/**
 * REST client for {{ApiName}}.
 * Uses Spring RestClient (Spring 6.1+ / Boot 3.2+).
 * 
 * Recommended for:
 * - External/legacy APIs (maximum flexibility)
 * - Non-standardized APIs
 * - When fine-grained control is needed
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (restclient variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@Slf4j
@Component
public class {{ApiName}}Client {
    
    private final RestClient restClient;
    private final String baseUrl;
    
    public {{ApiName}}Client(
            RestClient.Builder restClientBuilder,
            @Value("${integration.{{apiName}}.base-url}") String baseUrl) {
        this.baseUrl = baseUrl;
        this.restClient = restClientBuilder
            .baseUrl(baseUrl)
            .defaultStatusHandler(
                status -> status.is4xxClientError() || status.is5xxServerError(),
                (request, response) -> {
                    throw new IntegrationException(
                        "{{ApiName}} error: " + response.getStatusCode(),
                        response.getStatusCode().value()
                    );
                }
            )
            .build();
    }
    
    public {{Entity}}Dto getById(String id) {
        log.debug("{{ApiName}}: GET {{resourcePath}}/{}", id);
        
        return restClient.get()
            .uri("{{resourcePath}}/{id}", id)
            .headers(this::addCorrelationHeaders)
            .retrieve()
            .body({{Entity}}Dto.class);
    }
    
    public List<{{Entity}}Dto> getAll() {
        log.debug("{{ApiName}}: GET {{resourcePath}}");
        
        return restClient.get()
            .uri("{{resourcePath}}")
            .headers(this::addCorrelationHeaders)
            .retrieve()
            .body(new ParameterizedTypeReference<>() {});
    }
    
    public {{Entity}}Dto create({{Entity}}Dto dto) {
        log.debug("{{ApiName}}: POST {{resourcePath}}");
        
        return restClient.post()
            .uri("{{resourcePath}}")
            .headers(this::addCorrelationHeaders)
            .contentType(MediaType.APPLICATION_JSON)
            .body(dto)
            .retrieve()
            .body({{Entity}}Dto.class);
    }
    
    public {{Entity}}Dto update(String id, {{Entity}}Dto dto) {
        log.debug("{{ApiName}}: PUT {{resourcePath}}/{}", id);
        
        return restClient.put()
            .uri("{{resourcePath}}/{id}", id)
            .headers(this::addCorrelationHeaders)
            .contentType(MediaType.APPLICATION_JSON)
            .body(dto)
            .retrieve()
            .body({{Entity}}Dto.class);
    }
    
    public void delete(String id) {
        log.debug("{{ApiName}}: DELETE {{resourcePath}}/{}", id);
        
        restClient.delete()
            .uri("{{resourcePath}}/{id}", id)
            .headers(this::addCorrelationHeaders)
            .retrieve()
            .toBodilessEntity();
    }
    
    /**
     * Adds correlation headers for distributed tracing.
     * MANDATORY for all outbound requests.
     */
    private void addCorrelationHeaders(org.springframework.http.HttpHeaders headers) {
        String correlationId = MDC.get("correlationId");
        if (correlationId != null) {
            headers.set("X-Correlation-ID", correlationId);
        }
        headers.set("X-Source-System", "{{serviceName}}");
    }
}
