// Template: JpaEntity.java.tpl
// Output: {{basePackage}}/adapter/persistence/entity/{{Entity}}JpaEntity.java
// Purpose: JPA entity (ONLY in adapter layer, NOT in domain)

package {{basePackage}}.adapter.persistence.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * JPA entity for {{Entity}}.
 * 
 * IMPORTANT: JPA entities belong in ADAPTER layer, NOT domain.
 * Domain layer has pure POJOs without JPA annotations.
 * 
 * Generated by: mod-016-persistence-jpa-spring
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Entity
@Table(name = "{{tableName}}")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class {{Entity}}JpaEntity {
    
    @Id
    @Column(name = "id", length = 36)
    private String id;
    
{{#entityFields}}
    @Column(name = "{{columnName}}"{{#nullable}}, nullable = true{{/nullable}}{{^nullable}}, nullable = false{{/nullable}})
    private {{fieldType}} {{fieldName}};
    
{{/entityFields}}
    @Version
    @Column(name = "version")
    private Long version;
    
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
