// ═══════════════════════════════════════════════════════════════════════════════
// Template: Application.java.tpl
// Module: mod-code-015-hexagonal-base-java-spring
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackagePath}}/{{ServiceName}}Application.java
// Purpose: 
// ═══════════════════════════════════════════════════════════════════════════════
// REQUIRED VARIABLES: {{ServiceName}} {{basePackage}} {{serviceName}} 
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main application entry point for {{serviceName}}.
 * 
 * Generated by: skill-code-020-generate-microservice-java-spring
 * Module: mod-015-hexagonal-base-java-spring
 */
@SpringBootApplication
public class {{ServiceName}}Application {
    
    public static void main(String[] args) {
        SpringApplication.run({{ServiceName}}Application.class, args);
    }
}
