// Template: DomainService.java.tpl
// Output: {{basePackage}}/domain/service/{{Entity}}DomainService.java
// Purpose: Domain service (pure POJO with business logic)

package {{basePackage}}.domain.service;

import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.model.{{Entity}}Id;
import {{basePackage}}.domain.repository.{{Entity}}Repository;
import {{basePackage}}.domain.exception.{{Entity}}NotFoundException;

import java.util.List;

/**
 * Domain service for {{Entity}} business logic.
 * 
 * IMPORTANT: This is a pure POJO.
 * - NO Spring annotations (@Service, @Component)
 * - NO @Transactional (that's in application layer)
 * - Instantiated via @Bean in infrastructure config
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public class {{Entity}}DomainService {
    
    private final {{Entity}}Repository repository;
    
    public {{Entity}}DomainService({{Entity}}Repository repository) {
        this.repository = repository;
    }
    
    public {{Entity}} get{{Entity}}({{Entity}}Id id) {
        return repository.findById(id)
            .orElseThrow(() -> new {{Entity}}NotFoundException(id));
    }
    
    public List<{{Entity}}> getAll{{Entity}}s() {
        return repository.findAll();
    }
    
    public {{Entity}} create{{Entity}}({{#entityFields}}{{fieldType}} {{fieldName}}{{^last}}, {{/last}}{{/entityFields}}) {
        {{Entity}} entity = {{Entity}}.create({{#entityFields}}{{fieldName}}{{^last}}, {{/last}}{{/entityFields}});
        return repository.save(entity);
    }
    
    public void delete{{Entity}}({{Entity}}Id id) {
        // Verify exists
        get{{Entity}}(id);
        repository.deleteById(id);
    }
}
