// ═══════════════════════════════════════════════════════════════════════════════
// Template: Entity.java.tpl
// Module: mod-code-015-hexagonal-base-java-spring
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackagePath}}/domain/model/{{Entity}}.java
// Purpose: Domain entity (pure POJO, NO framework annotations)
// ═══════════════════════════════════════════════════════════════════════════════
// REQUIRED VARIABLES (must be in generation-context.json):
//   - {{basePackage}}      : Java base package (e.g., com.bank.customer)
//   - {{basePackagePath}}  : Package as path (e.g., com/bank/customer)
//   - {{Entity}}           : Entity name PascalCase (e.g., Customer)
//   - {{entityFields}}     : Array of {fieldName, fieldType, fieldNamePascal}
//   - {{entityImports}}    : Array of additional imports (e.g., java.time.LocalDate)
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}}.domain.model;

{{#entityImports}}
import {{.}};
{{/entityImports}}
import java.util.UUID;

/**
 * {{Entity}} domain entity.
 * 
 * IMPORTANT: This is a pure domain object.
 * - NO Spring annotations (@Entity, @Component, etc.)
 * - NO JPA annotations
 * - Business logic belongs here
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public class {{Entity}} {
    
    // TB-001 FIX: Removed 'final' - field is assigned via static factory methods
    private {{Entity}}Id id;
{{#entityFields}}
    private {{fieldType}} {{fieldName}};
{{/entityFields}}
    
    // Factory method for new entities
    public static {{Entity}} create({{#entityFields}}{{fieldType}} {{fieldName}}{{^last}}, {{/last}}{{/entityFields}}) {
        {{Entity}} entity = new {{Entity}}();
        entity.id = {{Entity}}Id.generate();
{{#entityFields}}
        entity.{{fieldName}} = {{fieldName}};
{{/entityFields}}
        return entity;
    }
    
    // Factory method for reconstitution from persistence
    public static {{Entity}} reconstitute({{Entity}}Id id{{#entityFields}}, {{fieldType}} {{fieldName}}{{/entityFields}}) {
        {{Entity}} entity = new {{Entity}}();
        entity.id = id;
{{#entityFields}}
        entity.{{fieldName}} = {{fieldName}};
{{/entityFields}}
        return entity;
    }
    
    private {{Entity}}() {}
    
    public {{Entity}}Id getId() {
        return id;
    }
    
{{#entityFields}}
    public {{fieldType}} get{{fieldNamePascal}}() {
        return {{fieldName}};
    }
    
{{/entityFields}}
    // Domain behavior methods go here
}
