// Template: Enum.java.tpl
// Output: {{basePackage}}/domain/model/{{EnumName}}.java
// Purpose: Domain enum (pure Java enum, NO framework annotations)

package {{basePackage}}.domain.model;

/**
 * {{EnumName}} domain enumeration.
 * 
 * IMPORTANT: This is a pure domain enum.
 * - NO Spring annotations
 * - NO JPA annotations
 * - Can contain behavior methods if needed
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public enum {{EnumName}} {
{{#enumValues}}
    {{value}}{{^last}},{{/last}}{{#last}};{{/last}}
{{/enumValues}}
    
{{#hasDescription}}
    private final String description;
    
    {{EnumName}}(String description) {
        this.description = description;
    }
    
    public String getDescription() {
        return description;
    }
{{/hasDescription}}
{{^hasDescription}}
    // Add behavior methods if needed
    // Example:
    // public boolean isActive() {
    //     return this == ACTIVE;
    // }
{{/hasDescription}}
}
