// ═══════════════════════════════════════════════════════════════════════════════
// Template: NotFoundException.java.tpl
// Module: mod-code-015-hexagonal-base-java-spring
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackagePath}}/domain/exception/{{Entity}}NotFoundException.java
// Purpose: Domain exception for entity not found
// ═══════════════════════════════════════════════════════════════════════════════
// REQUIRED VARIABLES (must be in generation-context.json):
//   - {{basePackage}}      : Java base package (e.g., com.bank.customer)
//   - {{basePackagePath}}  : Package as path (e.g., com/bank/customer)
//   - {{Entity}}           : Entity name PascalCase (e.g., Customer)
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}}.domain.exception;

import {{basePackage}}.domain.model.{{Entity}}Id;

/**
 * Exception thrown when {{Entity}} is not found.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public class {{Entity}}NotFoundException extends RuntimeException {
    
    private final {{Entity}}Id id;
    
    public {{Entity}}NotFoundException({{Entity}}Id id) {
        super("{{Entity}} not found with id: " + id.value());
        this.id = id;
    }
    
    public {{Entity}}Id getId() {
        return id;
    }
}
