// Template: NotFoundException.java.tpl
// Output: {{basePackage}}/domain/exception/{{Entity}}NotFoundException.java
// Purpose: Domain exception for entity not found

package {{basePackage}}.domain.exception;

import {{basePackage}}.domain.model.{{Entity}}Id;

/**
 * Exception thrown when {{Entity}} is not found.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public class {{Entity}}NotFoundException extends RuntimeException {
    
    private final {{Entity}}Id id;
    
    public {{Entity}}NotFoundException({{Entity}}Id id) {
        super("{{Entity}} not found with id: " + id.value());
        this.id = id;
    }
    
    public {{Entity}}Id getId() {
        return id;
    }
}
