// Template: Repository.java.tpl
// Output: {{basePackage}}/domain/repository/{{Entity}}Repository.java
// Purpose: Repository port (interface in domain layer)

package {{basePackage}}.domain.repository;

import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.model.{{Entity}}Id;

import java.util.List;
import java.util.Optional;

/**
 * Repository port for {{Entity}} persistence.
 * 
 * IMPORTANT: This is a PORT (interface) in the domain layer.
 * - NO Spring annotations
 * - NO implementation details
 * - Implementations live in adapter layer
 * 
 * CONTRACT (v1.3):
 * ─────────────────────────────────────────
 * Standard repository operations. All methods are part of the contract.
 * If an adapter cannot implement a method (e.g., System API doesn't support it),
 * the adapter should throw UnsupportedOperationException with clear message.
 * 
 * Generated by: mod-015-hexagonal-base-java-spring
 * ERI Reference: eri-code-001-hexagonal-light-java-spring
 */
public interface {{Entity}}Repository {
    
    /**
     * Find entity by ID.
     * @param id the entity ID
     * @return Optional containing the entity if found
     */
    Optional<{{Entity}}> findById({{Entity}}Id id);
    
    /**
     * Find all entities.
     * For System API backed persistence, typically maps to a list transaction.
     * May support pagination via overloaded method.
     * @return list of all entities
     */
    List<{{Entity}}> findAll();
    
    /**
     * Save entity (create or update).
     * @param entity the entity to save
     * @return the saved entity with generated ID if new
     */
    {{Entity}} save({{Entity}} entity);
    
    /**
     * Delete entity by ID.
     * @param id the entity ID
     * @throws UnsupportedOperationException if delete not supported by backend
     */
    void deleteById({{Entity}}Id id);
    
    /**
     * Check if entity exists by ID.
     * Default implementation can use findById(id).isPresent()
     * @param id the entity ID
     * @return true if exists
     */
    boolean existsById({{Entity}}Id id);
}
