// ═══════════════════════════════════════════════════════════════════════════════
// Template: restclient-config.java.tpl
// Module: mod-code-017-persistence-systemapi
// Variant: restclient
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackage}}/infrastructure/config/RestClientConfig.java
// Purpose: RestClient bean configuration with basic timeout protection
// ═══════════════════════════════════════════════════════════════════════════════
// REQUIRED VARIABLES: {{basePackage}}
// ═══════════════════════════════════════════════════════════════════════════════
// NOTE: Default timeouts are intentionally HIGH (30s/60s) as basic infrastructure
//       protection against infinite hangs. These are NOT resilience timeouts.
//       
//       For resilience-level timeouts (e.g., 5s/10s), use mod-003 (timeout) in 
//       Phase 3, which will MODIFY these values according to resilience requirements.
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}}.infrastructure.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.client.ClientHttpRequestFactory;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.web.client.RestClient;

import java.time.Duration;

/**
 * RestClient configuration with basic timeout protection.
 * 
 * Default timeouts are set HIGH (30s connect, 60s read) as infrastructure-level
 * protection against infinite hangs. These values prevent connections from
 * hanging indefinitely but are NOT intended as resilience timeouts.
 * 
 * For resilience requirements (circuit breaker, retry, fine-grained timeouts),
 * cross-cutting modules (mod-001, mod-002, mod-003) will modify this configuration
 * in Phase 3 of code generation.
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (restclient variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@Configuration
public class RestClientConfig {
    
    /**
     * Connection timeout - time to establish TCP connection.
     * Default: 30s (high, infrastructure protection only)
     */
    @Value("${integration.http.connect-timeout:30s}")
    private Duration connectTimeout;
    
    /**
     * Read timeout - time to receive response data.
     * Default: 60s (high, infrastructure protection only)
     */
    @Value("${integration.http.read-timeout:60s}")
    private Duration readTimeout;
    
    @Bean
    public RestClient.Builder restClientBuilder() {
        return RestClient.builder()
            .requestFactory(clientHttpRequestFactory());
    }
    
    @Bean
    public ClientHttpRequestFactory clientHttpRequestFactory() {
        SimpleClientHttpRequestFactory factory = new SimpleClientHttpRequestFactory();
        factory.setConnectTimeout(connectTimeout);
        factory.setReadTimeout(readTimeout);
        return factory;
    }
}
