// Template: IntegrationException.java.tpl
// Output: {{basePackage}}/adapter/integration/exception/IntegrationException.java
// Purpose: Exception for API integration failures

package {{basePackage}}.adapter.integration.exception;

/**
 * Exception thrown when API integration fails.
 * Includes HTTP status code for proper error handling.
 * 
 * Generated by: mod-018-api-integration-rest-java-spring
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
public class IntegrationException extends RuntimeException {
    
    private final int statusCode;
    
    public IntegrationException(String message, int statusCode) {
        super(message);
        this.statusCode = statusCode;
    }
    
    public IntegrationException(String message, int statusCode, Throwable cause) {
        super(message, cause);
        this.statusCode = statusCode;
    }
    
    public int getStatusCode() {
        return statusCode;
    }
    
    public boolean isClientError() {
        return statusCode >= 400 && statusCode < 500;
    }
    
    public boolean isServerError() {
        return statusCode >= 500;
    }
}
